⚠️ Dropping 2893 rows with invalid timestamps
Traceback (most recent call last):
  File "D:\logai-main\logai\elastic_wrapper.py", line 108, in <module>
    .size()
  File "C:\Users\cg722v\Miniconda3\envs\logai-py310\lib\site-packages\pandas\core\window\rolling.py", line 321, in __getattr__
    raise AttributeError(
AttributeError: 'RollingGroupby' object has no attribute 'size'
